# Generated by Django 5.1.4 on 2025-10-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_gallery_deleted_at_gallery_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='homebanner',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='homebanner',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='products',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_deleted',
        ),
    ]
