# Generated by Django 5.2.9 on 2025-12-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_gallery_deleted_at_remove_gallery_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gif_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif_image', models.ImageField(upload_to='gifs/')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Gif Section',
                'verbose_name_plural': 'Gif Sections',
            },
        ),
    ]
